### ISSUE TITLE
Token issue with ecobee API

### ISSUE THREAD

**Issue by timolow** [watou/vera-ecobee#21]
Running v1.3 of ecobee plugin on vera egde and have been getting "ecobee : Not yet authorized. Press 'Get PIN' once; wait for PIN; enter at ecobee.com."  once or twice per day.

LuaUPnP.log:50	01/14/16 13:56:26.101	luup_log:4: ecobee: task: Not yet authorized. Press 'Get PIN' once; wait for PIN; enter at ecobee.com. <0x76b01520>
LuaUPnP.log:50	01/14/16 13:59:26.008	luup_log:4: ecobee: task: Not yet authorized. Press 'Get PIN' once; wait for PIN; enter at ecobee.com. <0x76b01520>
LuaUPnP.log:50	01/14/16 14:02:26.089	luup_log:4: ecobee: task: Not yet authorized. Press 'Get PIN' once; wait for PIN; enter at ecobee.com. <0x76b01520>
LuaUPnP.log:50	01/14/16 14:05:26.101	luup_log:4: ecobee: task: Not yet authorized. Press 'Get PIN' once; wait for PIN; enter at ecobee.com. <0x76b01520>
LuaUPnP.log:50	01/14/16 14:08:26.101	luup_log:4: ecobee: task: Not yet authorized. Press 'Get PIN' once; wait for PIN; enter at ecobee.com. <0x76b01520>

**Comment by watou** [comment]
The v1.3 plugin discards the auth token after 5 consecutive failures, but those failures could be of any sort, such as Internet problems, the Ecobee API is down, etc.  Connectivity or service availability outages lasting 15 minutes or more (polling every three minutes, fails five times) can cause the auth token to be discarded in v1.3. This is most likely the cause of prematurely discarded tokens.

I have tested a change for v1.4 that will only discard the auth token when an attempt to refresh tokens returns the following JSON response:
```json
{
  "error": "invalid_client",
  "error_description": "Authentication error, invalid authentication method, lack of credentials, etc.",
  "error_uri": "http://tools.ietf.org/html/draft-ietf-oauth-v2-31#section-5.2"
}
```
specifically, if the response has an error of "invalid_client".  So this means all failures due to network or any other problems are ignored, and the plugin will continue to attempt to refresh tokens until it is explicitly told its current refresh or auth token is rubbish, with an "invalid_client" response.

**Comment by jcb79** [comment]
Thanks for starting this bug report.  I have been experiencing this issue for some time myself.  Finally decided to deal with it today and found this thread.
