### ISSUE TITLE
lzoenc?

### ISSUE THREAD

**Issue by rafale77** [watou/vera-ecobee#41]
I am trying to implement this plugin with some modifications on Openluup. The license says it is free and can be modified but there is an encrypted. Would you be so kind as to share that encrypted file?

**Comment by watou** [comment]
The attached file `L_ecobee.lua` differs from the encrypted one in that the real `client_id` used in the plugin at apps.mios.com has been replaced with `YOU NEED YOUR OWN CLIENT ID HERE`.  It is not wise to publish the plugin with the common `client_id` so that it could be read and used by other, unrelated code.  Ecobee strongly discourages developers from sharing this code in plain text, hence the encrypted version of the file.  So to make the plugin work with Openluup, if it does not support encryption or otherwise hiding the `client_id`, would probably require that each user of the plugin creates their own free app and client_ID, and then enters it as a device variable or other configuration value in their plugin settings.  (See [this doc](https://docs.openhab.org/addons/bindings/ecobee1/readme.html#prerequisites) for suggestions on this).

So I hope that explanation, and the attached file, are helpful to you!


[L_ecobee.lua.txt](https://github.com/watou/vera-ecobee/files/1952319/L_ecobee.lua.txt)

**Comment by rafale77** [comment]
Got it. Thank you!
